name: 'Get Cache'
description: 'Gets node modules cache'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: "===== Build ====="
      shell: bash
      run: npm run build
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./build