name: PR
on:
  pull_request:
    branches: [ main ]
concurrency:
  group: on-pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  Install-And-Cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
  Build:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
      - name: "===== Build ====="
        run: npm run build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
  Lint:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
      - name: "===== Lint ====="
        run: npm run lint
  UnitTest:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
      - name: "===== Unit Tests ====="
        run: npm run test:ci
