name: PR
on:
  pull_request:
    branches: [ main ]
concurrency:
  group: on-pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  install-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
  build:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
  lint:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
      - name: "===== Lint ====="
        run: npm run lint
  unit-test:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
      - name: "===== Unit Tests ====="
        run: npm run test:ci
