name: PR
on:
  pull_request:
    branches: [ main ]
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  Install-And-Cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: "===== Install ====="
        run: npm ci
  Build:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: ./.github/actions/cache
      - name: "===== Build ====="
        run: npm run build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app-${{ github.head_ref || github.run_id  }}
          path: ./build
  Lint:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
      - name: "===== Lint ====="
        run: npm run lint
  UnitTest:
    runs-on: ubuntu-latest
    needs: Install-And-Cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache
      - name: "===== Unit Tests ====="
        run: npm run test:ci
